### ISSUE TITLE
idk what error i'm getting too

### ISSUE THREAD

**Issue by ItsG77** [jas3333/gptchat_pinecone#10]
Hello, i did everything according to the tutorial but i can't seem to get it working, my error is;

$ node server.js
file:///C:/Program%20Files/Git/gptchat_pinecone/node_modules/axios/lib/adapters/
http.js:7
import {getProxyForUrl} from 'proxy-from-env';
        ^^^^^^^^^^^^^^
SyntaxError: The requested module 'proxy-from-env' does not provide an export na
med 'getProxyForUrl'
←[90m    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)←[3
9m
←[90m    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)←[39m

←[90m    at async Loader.import (internal/modules/esm/loader.js:179:24)←[39m

My .env file: 

PORT=5000 # This will change the port the express server uses.
 OPEN_AI_KEY=(API KEY)
 PINECONE_API=(API KEY)
 QUERY_URL=https://memory-dd6156a.svc.us-central1-gcp.pinecone.io/query # Insert your index location here, and make sure /query is on the end
 UPSERT_URL=https://memory-dd6156a.svc.us-central1-gcp.pinecone.io/vectors/upsert # Insert your indexlocation here and make sure /vectors/upsert is on the end
 MONGODB=mongodb://localhost:27017/memories # Put in your mongodb connection string here
 topK=3 # This determines how many related matches are injected into the prompt, keep it at 2 or 3 to keep tokens low

**Comment by revbin** [comment]
try to use a Nodejs version superior to 14 (18 best) .

for more info : https://github.com/axios/axios/issues/5221
