### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by revbin** [jas3333/gptchat_pinecone#12]
hi

it will be best if the search and injection side have this project features https://github.com/Jordan-Gilliam/ai-template

they already implemented scrape website and different document format upload to pinecone.

why i don't use it because this project rock !

**Comment by jas3333** [comment]
I would suggest you use the other project. While scraping is something I want to eventually get to, I have a lot of other things I need to do first so it would be awhile. This app still needs proper error handling, the UIs css is also a mess, and I need to get it mobile friendly.

**Comment by revbin** [comment]
just for info i will continue use your script because have all what i need for now and like it .

for future features i will wait .
