### ISSUE TITLE
Add milvus or Weaviate as vector DB

### ISSUE THREAD

**Issue by revbin** [jas3333/gptchat_pinecone#14]
hi

its possible to add milvus or Weaviate solution like pinecone env .the thing is we can deploy milvus or weaviate in our home lab without restriction we have with starter pinecone pack.
info :
https://milvus.io/docs/overview.md
https://weaviate.io/        

regards

**Comment by jas3333** [comment]
Yeah I was looking into Milvus and then got distracted with re-writing this app in Solidjs. I'll probably mess around with it on my next weekend.

**Comment by revbin** [comment]
any update for the new website with milvus ? :)

**Comment by jas3333** [comment]
I'm not going to be able to get to it for awhile.  I briefly looked at the docs and it isn't very straight forward and easy to setup like Pinecone. I'm currently working on a work project that is going to be taking up a lot of my time so this will have to get put on the back burner for now.

**Comment by revbin** [comment]
thx any way . good luck with your actual projects .
