### ISSUE TITLE
Add the ability to import documents into the databases 

### ISSUE THREAD

**Issue by revbin** [jas3333/gptchat_pinecone#2]
Hi

First thx a lot for this website and for sharing your knowledge's. i know this is in roadmap but this feature is game changer for  a lot of us since we can add infinite abilities to gpt3.5 or gpt4.
i hope this will be implemented.

thanks in advance

**Comment by jas3333** [comment]
Yeah I haven't decided how I will go about doing this. I've written scripts that get it done, I just need to make them user friendly as currently I have the documents(file names, and locations) hard coded into the script. I don't think I want to have the site do it because it can take a very long time(20+ minutes) to process depending on the document size.

**Comment by revbin** [comment]
any solution is welcome since we can add our datasets to the BD as AI memories.

if you don't mind can you please share your written script . i will work on it too .

**Comment by jas3333** [comment]
Ok I pushed an update that includes the script. Currently only does PDFs.

**Comment by revbin** [comment]
Hi
you can take a look at this , its what we want to do .
Video: https://www.youtube.com/watch?v=tBJ-CTKG2dM.
code:  https://github.com/pinecone-io/examples/blob/master/generation/gpt4-retrieval-augmentation/gpt-4-langchain-docs.ipynb
if the integration is so slow in website we can just create a companion script just to upload our datasets fast to the DB with user friendly manners .
regards

**Comment by jas3333** [comment]
> Hi you can take a look at this , its what we want to do . Video: https://www.youtube.com/watch?v=tBJ-CTKG2dM. code: https://github.com/pinecone-io/examples/blob/master/generation/gpt4-retrieval-augmentation/gpt-4-langchain-docs.ipynb if the integration is so slow in website we can just create a companion script just to upload our datasets fast to the DB with user friendly manners . regards

Yeah, the way it's setup currently is pretty much as described in the video. Just need to add a script to scrape HTML then upload to DBs. The tricky part and something I'm still experimenting with is how to inject the vector query text into the prompt. Currently it's setup like:
```javascript
const prompt = `Context: ${messages}\n${conversationInjection} User: ${req.body.promptQuestion}`;

```
Where messages is the vector text and conversationInjection is the previous promptQuestions. I also setup a filter to filter out low scored vector queries.

**Comment by revbin** [comment]
Hi
now with last update we have 2 errors running the script. those errors happen when we chat with the gpt bot (the **API Key** is **correct**).
![1](https://user-images.githubusercontent.com/24886056/226146975-d1124a5a-171e-475d-a141-67baeb6440a3.png)
![2](https://user-images.githubusercontent.com/24886056/226146978-e1b68f93-b8c9-46ea-9ffb-68d0650416ae.png)

for python script look working but after some time he get blocked by OpenAi Api for excessive requests (look like we ddos ada embedded API)

![4](https://user-images.githubusercontent.com/24886056/226150974-2e6f9284-7d9a-456c-a5e9-163c36b6db75.png)

![5](https://user-images.githubusercontent.com/24886056/226151173-be57fbad-bb6f-43fd-b69e-79d2ee759f6e.png)

regards

**Comment by jas3333** [comment]
Looks like openai is having issues right now or something. I also don't know why some of the vector queries return messed up. I noticed while running the script some of the get embedding calls seems to fail. I should put a retry in that part of the script to retry if it fails. Probably has something to do with the issue.

**Comment by revbin** [comment]
i will test tomorrow . i will keep you updated if the issue still occurs for python script and gptController.js .

**Comment by jas3333** [comment]
I moved the filtering of the ids and mongo query into a separate function to try and catch the error that causes the server to crash.

**Comment by revbin** [comment]
look at this project , he did what you want to do without $persona.
https://github.com/Zeeshanahmad4/chatgpt-knowledge-base-chatbot/tree/main

**Comment by jas3333** [comment]
> look at this project , he did what you want to do without $persona. https://github.com/Zeeshanahmad4/chatgpt-knowledge-base-chatbot/tree/main

His source code is pretty empty. Basically does nothing right now.

**Comment by revbin** [comment]
tested this solution and its working fine 

https://github.com/mayooear/gpt4-pdf-chatbot-langchain
