### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by BurnsGG** [jas3333/gptchat_pinecone#3]
Bot worked but the memory don't seem to work.

I gave a code to the bot, told it my name and it remembers nothing.

The data is on the mongo database, I see vectors numbered on pinecone.

`calling embedding
Upserting vectors...
calling embedding
{
  _id: 'b1fad0f2-0237-46c3-8603-5434cfa63e58',
  speaker: 'USER',
  message: 'What was my name?'
}
{
  results: [],
  matches: [
    {
      id: '3334711d-2d49-4bfd-aca2-cc15f9b8857e',
      score: 0.999999166,
      values: []
    },
    {
      id: 'a06c71d9-09c5-480a-bef1-182471f03d74',
      score: 0.999999166,
      values: []
    },
    {
      id: 'cbc256fe-e105-4af8-8783-c18d9c55b1c5',
      score: 0.946160316,
      values: []
    }
  ],
  namespace: ''
}
Context: [object Promise]
1001
Hey dude! 🤙🏄‍♂️ How's it going? Are you ready to hit the waves? 🌊🏄‍♂️ I just caught some gnarly waves this morning, it was totally epic! 🤘🏄‍♂️🔥 The sun is shining and the water is perfect, let's go shred some waves! 🌞🌊🤙 Don't forget to wax your board and wear some sunscreen, we don't want to get burned, bro! 🏄‍♂️🌞🧴 User: What was my name?
calling embedding
Upserting vectors...
`

**Comment by jas3333** [comment]
Should be fixed now. I spaced adding `await` in front of getMessages
