### ISSUE TITLE
Persona issue

### ISSUE THREAD

**Issue by revbin** [jas3333/gptchat_pinecone#4]
Hi

i modified the persona to meet my needs. but some of them is working and some of them not after the last update.

for example for Pentester bot he didn't catch the persona prompt i setup even in the http request i have the right persona ID.

i attached my customs personas js file maybe you want to take look at it.

[personas.js.txt](https://github.com/jas3333/gptchat_pinecone/files/11012622/personas.js.txt)
[main.2dfe6af5.js.map.txt](https://github.com/jas3333/gptchat_pinecone/files/11012656/main.2dfe6af5.js.map.txt)
[Settings.jsx.txt](https://github.com/jas3333/gptchat_pinecone/files/11012657/Settings.jsx.txt)
[main.2dfe6af5.js.txt](https://github.com/jas3333/gptchat_pinecone/files/11012658/main.2dfe6af5.js.txt)

**Comment by jas3333** [comment]
I don't see any issues. Try resetting the conversation when switching personas or they will take some of the previous conversation into account.

**Comment by revbin** [comment]
hi
i already did that . here is screenshot for example.
**Pentester** persona which not work , he should give his persona name
![unpersona](https://user-images.githubusercontent.com/24886056/226227323-99db9952-45cb-4010-9bf4-7c9f85244508.png)

a woking example with Developer persona

![persona](https://user-images.githubusercontent.com/24886056/226227402-3b3b6c75-c31b-494f-9cff-db081889431d.png)

**Comment by jas3333** [comment]
Try shortening up the prompt a bit. Copy and paste it into one of the bots and have them summarize it then use the summarized text for the Jack persona.

**Comment by revbin** [comment]
did that, rewrited Jack prompt and still same issue. before the update was working .
i will dig deeper this week what happen .(spent all day today with no clue what happen)

**Comment by revbin** [comment]
Hi
tested this with the  old branch before the last  updates and its worked without any problem (i attached the modified persona files)
used the same modified persona with latest branch update and its does not work .so its not the value of $persona is our problem i think something in new gptController.js file .
[personas.js.txt](https://github.com/jas3333/gptchat_pinecone/files/11035758/personas.js.txt)

regards

**Comment by jas3333** [comment]
It's not the gptController. Add this anywhere inside of the sendQuestion function inside gptController.js:
```javascript
console.log(`Current Persona: ${personas[req.body.persona].prompt}`)
```

Then check the server log to see which persona is getting passed to the API.

**Comment by revbin** [comment]
Hi
did your recommendation . and the right prompt sent in HTTP request. but for unknown reasons the API does not recognize his name. 
![personavalid](https://user-images.githubusercontent.com/24886056/226980101-84586fcd-a4ac-40c6-bf51-a41973eaac32.png)

regards

**Comment by jas3333** [comment]
Try setting the temperature to 0 and top_p to 0.7ish. A lower temperature seems to follow the system prompt better.

**Comment by revbin** [comment]
Hi
i reset the chat, opened a new window and its same result. its a weird behavour .
![personavalid0](https://user-images.githubusercontent.com/24886056/226990598-25539085-cb2c-4c8c-bd14-74a7ef86527f.png)

**Comment by revbin** [comment]
i give up ..... you can close this Issue.

**Comment by jas3333** [comment]
Well at this point looks like it's also reading the context from the vector DB and mongo. You could try finding and deleting those. I think you can query from the Pinecone website, and for mongo you can get Compass to show your databases.

**Comment by revbin** [comment]
hi 
just for record i fixed the problem by changing this in gptController.js
```
const prompt = `Context: ${messages}\n${conversationInjection} User: ${req.body.promptQuestion}`;
```
to
```
const prompt = `Context: ${messages}\n${personas[req.body.persona].name}\n${conversationInjection} User: ${req.body.promptQuestion}`;
 ```

regards
