### ISSUE TITLE
Semantic Search & Injection

### ISSUE THREAD

**Issue by revbin** [jas3333/gptchat_pinecone#9]
hi

seems the Semantic Search & Injection does not work or i miss something ?

![palo-script](https://user-images.githubusercontent.com/24886056/229310571-4f46aa98-f519-4fc3-927c-ae2657053639.png)

regards

**Comment by revbin** [comment]
Hi
find my issue. there is anyway to change pinecone server listen on 0.0.0.0 not localhost ?

![palo-01001](https://user-images.githubusercontent.com/24886056/229310860-24e8e1ab-b543-4e5b-a0dd-27ddf8e26f81.png)

**Comment by jas3333** [comment]
Ahh oops, I think I see the issue. I'll change it to `/api/v1/pine` instead of `http://localhost:4005/api/v1/pine`. Remnants from testing. Can you try again and let me know if it works?

**Comment by revbin** [comment]
now i can make POST request without errors  but there  is no result . like it does not catch the pinecone server response.
![empty](https://user-images.githubusercontent.com/24886056/229312236-7db78418-6afc-4e60-b484-a0a83122b345.png)

**Comment by jas3333** [comment]
I wonder if it's the live search, I noticed that if I don't hit space after my search it can give weird results.

**Comment by revbin** [comment]
i hit the space that how i have the Pinecone POST request . and always have the same issue : empty msg.

**Comment by jas3333** [comment]
Can you try editing the pineController.js file and change 0.79 to a lower number? It will reject everything if it doesn't have a high enough score. 

```js
 const messages = await getMessages(pineconeResults, 0.79);
```

**Comment by revbin** [comment]
lowered to 0.40 and still empty msg for all pinecone API . the live search is working because i saw many HTTP POST requests when i type my msg  but all of them have empty msg responses.

**Comment by jas3333** [comment]
Ok I disabled the live search, so now when you search hit enter. Also check the server log it should be logging returned results.

**Comment by revbin** [comment]
same issue , maybe my pinecone database ? i used the python script to insert vectors .
server log when i search 
![logserv02](https://user-images.githubusercontent.com/24886056/229314030-7e365b6e-1e2e-481a-a241-1fb1c7f9ed3b.png)
http POST response
![logserv01](https://user-images.githubusercontent.com/24886056/229314065-7af845f0-10ee-40b6-806d-4374f74baa18.png)

**Comment by jas3333** [comment]
I added another log to the server, look for `query: ` in the log and see if something shows up.

**Comment by revbin** [comment]
Hi
here is the log. i think something messing in POST pinecone request API .
![API pinecone](https://user-images.githubusercontent.com/24886056/229314560-f468f95a-8b57-4214-b409-b38463057605.png)

**Comment by jas3333** [comment]
That is weird, I'm not sure what is wrong. Everything is working on my end. Have you tried searching for other things? Like ask the bot something then copy paste some of the response into the vector search and see if it shows up.

**Comment by revbin** [comment]
i tested many times by  copied text from a vectored pdf  and always same result .Semantic Search & Injection never worked for me .

**Comment by revbin** [comment]
well, make it work But....so it only work with already previous asked prompt , it does not search in Pinecone database .
also i noticed the response is duplicated as in screenshot .
 
![logserv04](https://user-images.githubusercontent.com/24886056/229320102-a542d43a-4cc9-41be-a49e-5eac8efca99a.png)

**Comment by jas3333** [comment]
That's weird it's showing up twice. I haven't seen that happen. 

It's showing the previously asked prompt because while you're chatting it's also uploading the chats to the databases. So if you want to keep a part of the conversation in memory you can  search the database and select the previous chat and it will always be injected as long as it selected. Keep in mind if you search for something new and had something selected it will still be in the memory array. 

Also I think the python script needs a while loop for the embeddings section as it was producing blanks a couple of weeks ago. I believe OpenAI was having issues.  I have used it to upload one book and it's mostly there and shows up in my searches.

**Comment by revbin** [comment]
can we have the python script updated with a loop for  the embeddings section, i will delete my current Pinecone DB and create one from scratch and test again .i think my pinecone DB is mess up at this point .

**Comment by jas3333** [comment]
Ok I've updated it. I didn't have time to test it. The script itself needs a lot of work and I'm not going to be working on it for a bit. I'll try to make it better on my next weekend.

**Comment by revbin** [comment]
thx a lot , i will test the whole week and will keep you updated .

**Comment by jas3333** [comment]
I think I found the issue as to why nothing was showing up. I had the wrong env name for the database name. So it was putting it into a DB called None. I've fixed it to match the readme instructions.

**Comment by revbin** [comment]
well now i have accurate responses with bots but still same issue Semantic Search & Injection 
always i got empty responses even i deleted my old pinecone DB with a new one .
![dbs02](https://user-images.githubusercontent.com/24886056/229330488-798861dc-0557-4719-a023-19090fd60e01.png)
im sure  the vectored pdf is in database 
![dbs01](https://user-images.githubusercontent.com/24886056/229330492-98a5b154-4569-4224-820f-f111dc5d32d9.png)
and my DB config its correct and still the Semantic Search & Injection does not search in DB for unknown reasons .
![dbs03](https://user-images.githubusercontent.com/24886056/229330539-ff4cc0d8-46b0-4303-a2d0-36332c7052af.png)
![dbs04](https://user-images.githubusercontent.com/24886056/229330544-1b27c73d-6c98-455c-8412-394f7a8d6b53.png)

**Comment by jas3333** [comment]
Have you tried the script since my last update(3 days ago)? The script was looking for `mongo_database_name` when the readme said `mongo_db_name`. When I updated it, it started dumping into the right DB.

**Comment by revbin** [comment]
> Have you tried the script since my last update(3 days ago)? The script was looking for `mongo_database_name` when the readme said `mongo_db_name`. When I updated it, it started dumping into the right DB.

Yes as in my previous post its dump in the right DB but the only result i get its a previous chat bots. it does not query 
information from vectored pdf in DB or pinecone DB .

**EDIT**
in my DB have 2 collection. i think your script just query the messages collection and does not search info in memory collection where is stored the vectored PDF.
![collections](https://user-images.githubusercontent.com/24886056/229978857-ccf661e0-5355-471f-9edf-99ae768f7b8d.png)

**Comment by jas3333** [comment]
Ah yeah, you're right. I spaced that mongoose schemas will auto create a collection and it will be messages. I'll just hard code the collection into the script to match the app.

**Comment by revbin** [comment]
its worked . but the search show raw data from DB , it does not render it (like /n) also its show messed information.
for example:
![collections00](https://user-images.githubusercontent.com/24886056/230147130-80738498-0e15-4d9a-99c3-8735abc8f2ec.png)

it will be nice if the search and injection feature is like this project hxxps://github.com/mayooear/gpt4-pdf-chatbot-langchain

**Comment by jas3333** [comment]
Ok, try now. The `\n` should be removed now and add actual new lines.

Also check the README I updated the .env requirements, so just need `PINECONE_URL=indexlocation`  instead of the `query and upsert`

Also I should add this does the exact same thing as that other project. The only difference is there isn't a persona dedicated to reading from just the context. In the back ground it's auto injecting similar vector data, but on top of that you can manually search and inject.

**Comment by revbin** [comment]
now the python script fail to inject vector in pinecone .i got this error
![pyscript](https://user-images.githubusercontent.com/24886056/230252237-1743d7c3-4275-4141-b20c-32d2d9e11f56.png)
my env var
```
 PORT=5000 # This will change the port the express server uses.
 OPEN_AI_KEY=API_KEY
 PINECONE_API=API_KEY
 PINECONE_URL=https://something.svc.us-east-1-aws.pinecone.io # Insert your index location here
 MONGODB=mongodb://0.0.0.0:27017/datasets # Put in your mongodb connection string here topK=3 # This determines how many related matches are injected into the prompt, keep it at 2 or 3 to keep tokens low
 topK=3 # This determines how many related matches are injected into the prompt, keep it at 2 or 3 to keep tokens low

and for python script

OPEN_AI_KEY=API_KEY
PINECONE_API=API_KEY
MONGODB=mongodb://0.0.0.0:27017 
PINECONE_ENV=us-east-1-aws
pinecone_index=something
mongo_db_name=datasets
```

**Comment by jas3333** [comment]
That looks like the call to ADA is failing which is an OpenAI issue. It will keep looping until it's successful and looks like some were.

**Comment by revbin** [comment]
> That looks like the call to ADA is failing which is an OpenAI issue. It will keep looping until it's successful and looks like some were.

i think i got my issue . OpenAi API issue. i fix it and im trying again .

**Comment by revbin** [comment]
i was able to export a pdf to a pinecone DB and MongoDB. when we chat with Bots or make a search i always have this error .
the script cannot get the matched query from pinecone DB .
![pinescript](https://user-images.githubusercontent.com/24886056/230266091-3c301ef9-7178-48d4-81a1-90629c0f47d6.png)

**Comment by jas3333** [comment]
Looks like another OpenAI issue. When it sends off to OpenAI embedding it's not returning anything so when it queries the Pinecone index it's sending blanks.

**Comment by revbin** [comment]
i will test more tomorrow, maybe i will have some luck with OpenAi API.

**Comment by revbin** [comment]
i tested many time and always i get this error. i don't think is OpenAi API issue . there is something wrong with embedding https request in script side .

**Comment by jas3333** [comment]
If there was an issue with the code I would be having issues too. It's working fine. Double check your .env or something.

**Comment by revbin** [comment]
just for record i resolved my issue by creating a new DB in pinecone and now is working fine .
thx a lot for your help and the script .
